### ISSUE TITLE
G5 JS behaves differently on twitpic

### ISSUE THREAD

**Issue by GoogleCodeExporter** [classilla/tenfourfox#106]
```
The Twitpic image manipulation overlay appears fine on G4/7450 and reference 
Windows Firefox. It will not reappear on G5.
```

Original issue reported on code.google.com by `classi...@floodgap.com` on 7 Nov 2011 at 3:43
* Blocked on: #96

**Comment by classilla** [comment]
Closing since twitpic exhibits no difference now between 7450 and G5 (and doesn't seem to be properly working anyway).
