### ISSUE TITLE
AltiVec WebRTC

### ISSUE THREAD

**Issue by GoogleCodeExporter** [classilla/tenfourfox#250]
```
WebRTC is not fully supported (or well-tested), but there are SSE2 targets that 
should be amenable to AltiVec conversion.

media/webrtc/trunk/webrtc/modules/audio_processing/aec/aec_core_sse2.c

media/webrtc/trunk/webrtc/modules/audio_processing/aec/aec_rdft_sse2.c

media/webrtc/trunk/webrtc/modules/video_processing/main/source/content_analysis_
sse2.cc
```

Original issue reported on code.google.com by `classi...@floodgap.com` on 29 Oct 2013 at 4:56
- Blocking: #73

**Comment by classilla** [comment]
WebRTC is pretty much a lost cause at this point.

**Comment by nemanjacosovic** [comment]
@classilla lost cause in general or for TFF?

**Comment by classilla** [comment]
> @classilla lost cause in general or for TFF?

For us specifically. We're really behind on it and it never performed well even when we were current. It's not enabled in current builds anyway.
