### ISSUE TITLE
AltiVec libsoundtouch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [classilla/tenfourfox#251]
```
Not sure how much payoff this is, but there is an MMX and SSE version.

media/libsoundtouch/src/sse_optimized.cpp
```

Original issue reported on code.google.com by `classi...@floodgap.com` on 29 Oct 2013 at 4:59
- Blocking: #73

**Comment by classilla** [comment]
It appears to be used for bending and manipulations in `dom/media`.
