### ISSUE TITLE
Font black list for ATSUI-incompatible webfonts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [classilla/tenfourfox#261]
```
Uplift from 
https://tenfourfox.tenderapp.com/discussions/problems/715-2430-crashes

Certain web fonts do not appear to be compatible with ATSUI or trigger bugs. On 
10.4, this generates warnings; on 10.5, this crashes the browser. This is due 
to Mozilla's changes in 24 that cause us to use ATSUI on both 10.4 and 10.5 (on 
10.5, previously they used a different code path).

Since the font name is identifiable, we should be able to intercept it before 
it becomes activated.
```

Original issue reported on code.google.com by `classi...@floodgap.com` on 7 Mar 2014 at 4:27

**Comment by internetzel** [comment]
Had some days of struggling to get CoreText work right with web fonts - and well, it seems to finally do it right now!
I don't think the issues are CoreText specific ones but rather general ATS issues, the proposed workarounds should apply to NSFonts and CGFonts as well.
Those workarounds may reduce the need for blacklisting fonts quite a bit - at least on 10.5 .

I managed to solve the following issues:
1. CoreText has severe difficulties with Fonts that don't have a valid post script name;
It may leak entire CTFontDescriptors, render garbled glyphs, whatever bad things you can imagine.
2. CoreText may arbitrarily mix up Fonts that have the same PostScript name but in fact aren't the same font.
3. CoreText tends to return fallback fonts when using the functions CTFontCreateCopyWith... for modifying existing CTFontRefs (at least for many web fonts).

Issue 1 can be worked around by using OpenType Sanitizer - which Apple has refused to ever use. But sanitized fonts have identical font names, causing issue 2.

Issue 2 can be solved by changing ots to add a unique ID, like a hash value of the whole name table, to the sanitized PostScript name like in the following patch: [ots_name_table_patch.txt](https://github.com/classilla/tenfourfox/files/628354/ots_name_table_patch.txt)

Issue 3 can be worked around by following the rule to always create CTFontRefs (and CGFontRefs as well!) from the underlying ATSFontRefs, like this:
`CTFontDescriptorRef newDescriptor;`
`CTFontDescriptorRef descriptor = NULL;`
`ATSFontRef platformFont = CTFontGetPlatformFont(originalFont, &descriptor);`
`if (descriptor) {`
`newDescriptor = CTFontDescriptorCreateCopyWithAttributes(descriptor, attributes);`
`CFRelease(descriptor);`
`} else`
`newDescriptor = CTFontDescriptorCreateWithAttributes(attributes));`
`CTFontRef result = CTFontCreateWithPlatformFont(platformFont, CTFontGetSize(originalFont), nullptr, newDescriptor));`

**Comment by classilla** [comment]
I don't think most of that will work with the 10.4 SDK, but issue 2 is interesting to consider. I don't know if this is the actual cause of the glyph count mismatch, however.

**Comment by internetzel** [comment]
Now that I have discovered the issue with CTFontCreateWith... and web fonts activated using ATS (and maybe also CoreGraphics), I easily found that both Mozilla and Google (in Skia) discovered the same issue with basically the same fix:
[http://hg.mozilla.org/mozilla-central/rev/004e7ca095fb](http://hg.mozilla.org/mozilla-central/rev/004e7ca095fb)
[https://codereview.chromium.org/1344213004/](https://codereview.chromium.org/1344213004/)
[https://codereview.chromium.org/1362053003/](https://codereview.chromium.org/1362053003/)

I also found that there are still fonts that don't get assigned postscript name, although OTS didn't find and issue; that's easily detected.
But there are also fonts that seem to activate OK but don't really work later on (eventually causing crashes). Those can be detected by verifying that the underlying ATSFontRef stays the same after changing a CTFont's size:
`CTFontRef ctFontCandidate = CTFontCreateWithPlatformFont(atsFontRef, 0, nullptr, nullptr);`
`if(CTFontGetPlatformFont(CTFontCreateWithPlatformFont(CTFontGetPlatformFont(ctFontCandidate, nullptr), CTFontGetSize(ctFontCandidate) * 2, nullptr, nullptr), nullptr) == atsFontRef)`
It seems that might also work with 10.4's CoreText - even if you don't really need a CoreText font.
That way when going to [http://www.nytimes.com/2015/07/01/sports/the-most-dangerous-game.html?_r=0](http://www.nytimes.com/2015/07/01/sports/the-most-dangerous-game.html?_r=0) I get the following console messages:
`17.12.16 11:15:41 /System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Support/ATSServer[545] ********* Bad On-Memory Font Detected ********* (fontID = 16777519)`
`17.12.16 11:15:40 com.apple.ATSServer[545] FODBError: FODBRemoveFromAnnex - Got called to remove an annexIndex that does not match what is in the font`
The font is rejected by the pasted size change validation code and no crash occurs.
