### ISSUE TITLE
Enable ICU support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [classilla/tenfourfox#304]
```
Full ICU support will not be possible until we deal with issue 266, but we can 
implement stubs. 38 will have a stub normalize() that should be sufficient to 
fix Zotero.
```

Original issue reported on code.google.com by `classi...@floodgap.com` on 2 Jul 2015 at 3:48
* Blocked on: #266

**Comment by classilla** [comment]
This can be done with either the early patches from https://bugzilla.mozilla.org/show_bug.cgi?id=926980 or turning on MOZ_SHARED_ICU which will still be supported in 45. The latter is much simpler.

**Comment by classilla** [comment]
MOZ_SHARED_ICU it is.
