### ISSUE TITLE
jsonlz4 bookmark backups can't be processed

### ISSUE THREAD

**Issue by chris-chtrusch** [classilla/tenfourfox#307]
As reported in https://tenfourfox.tenderapp.com/discussions/problems/6852-all-my-bookmarks-and-all-my-toolbar-listings-gone.

Tested on 10.4 and 10.5, with TFF G3 and 7450. TFF 38.2.1

STR:
1) open Bookmarks library
2) click Import & Backup (Star) button>Restore
3) choose one of the backups to restore from

Result: error message "Unable to process the backup file". 

Research so far: TFF 38 changed the backup file format to jsonlz4. Old json backups can be processed. FF 38 ESR on Win XP can restore its own jsonlz4 files, but cannot process jsonlz4 files created by TFF 38 (same error message). Didn't find a correspondig bug at Bugzilla. I suspect that TFF doesn't write the jsonlz4format correctly.

**Comment by classilla** [comment]
Yeah, I saw this and I'm looking at it. A workaround might be just to revert to JSON-only bookmark backups but this is too late for 38.3.0.

**Comment by classilla** [comment]
Workaround placed. I'll test this more thoroughly when I get back from these conferences.

**Comment by classilla** [comment]
Fixed filename extension. Going to wontfix the larger issue unless something else depends on it, since it's just not worth smoking out.

**Comment by classilla** [comment]
One more tweak for manual bookmark backups.
