### ISSUE TITLE
'Going to Open ....' - is it possible to deactivate this message?

### ISSUE THREAD

**Issue by mrkapqa** [classilla/tenfourfox#315]
Hello ,

i would like that the QTE open the media in Quicktime files without asking prior for doing so. Is that somehw achivable?

Thank you very much.

Rich

**Comment by classilla** [comment]
Please don't open tickets for suggestions unless directed. That's what the Tenderapp site is for.

To answer your question, it's currently required by the way the QTE accesses the OS, so its presence is sort of a bug and feature at the same time.
