### ISSUE TITLE
Bugfix rollup for 38.10

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#321]
Non-general or non-OS X bugs not enumerated, but all changesets reviewed to date. I'll add more on Thursday.

Candidate bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1249578
https://bugzilla.mozilla.org/show_bug.cgi?id=1283823 (easy)
https://bugzilla.mozilla.org/show_bug.cgi?id=1279413 (easy)
https://bugzilla.mozilla.org/show_bug.cgi?id=1286183
https://bugzilla.mozilla.org/show_bug.cgi?id=1282502 (easy) (JS)
https://bugzilla.mozilla.org/show_bug.cgi?id=1268626 (easy) (JS)

Does not seem to apply:
https://bugzilla.mozilla.org/show_bug.cgi?id=1247949
https://bugzilla.mozilla.org/show_bug.cgi?id=1255270
https://bugzilla.mozilla.org/show_bug.cgi?id=1283067
https://bugzilla.mozilla.org/show_bug.cgi?id=1280043 (due to our configuration)
https://bugzilla.mozilla.org/show_bug.cgi?id=1282992
https://bugzilla.mozilla.org/show_bug.cgi?id=1257765 (we don't use this API)
https://bugzilla.mozilla.org/show_bug.cgi?id=1274637 (no GMP)
https://bugzilla.mozilla.org/show_bug.cgi?id=1275339
https://bugzilla.mozilla.org/show_bug.cgi?id=822081
https://bugzilla.mozilla.org/show_bug.cgi?id=1154923 (based on testing)
https://bugzilla.mozilla.org/show_bug.cgi?id=1258079
https://bugzilla.mozilla.org/show_bug.cgi?id=1279814
https://bugzilla.mozilla.org/show_bug.cgi?id=1240880
https://bugzilla.mozilla.org/show_bug.cgi?id=1250947
https://bugzilla.mozilla.org/show_bug.cgi?id=1272649
https://bugzilla.mozilla.org/show_bug.cgi?id=1268854

Will need work:
https://bugzilla.mozilla.org/show_bug.cgi?id=1278013 (using hints from https://bugzilla.mozilla.org/show_bug.cgi?id=1099296 to strip SEC_FORCE_INHERIT_PRINCIPAL from the loadinfo)

**Comment by polluks** [comment]
By the way the year in the about box is still 2015.

**Comment by classilla** [comment]
All candidates plus M1278013 landed and tested.
