### ISSUE TITLE
AltiVec vp9

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#324]
Some of the idcts and other components in vp9 look like they were written to aid easy vectorization. Assuming the compiler isn't doing that already, these look like good targets for gradual conversion.

**Comment by classilla** [comment]
Converted:
* vp9_convolve_avg_vmx
* vp9_convolve_copy_vmx
* vp9_idct16x16_1_add_vmx
* vp9_idct32x32_1_add_vmx
* vp9_idct4x4_16_add_vmx
* vp9_idct4x4_1_add_vmx
* vp9_idct8x8_1_add_vmx
* vp9_iht4x4_16_add_vmx

Also killed the loop filter, which helped quite a bit as well.

**Comment by classilla** [comment]
Whew!
Next intraframe predictors.

[idct.txt](https://github.com/classilla/tenfourfox/files/531479/idct.txt)

**Comment by barracuda156** [comment]
@classilla Could this be ported to modern `libvpx`? It dropped its own Altivec-without-VSX support several versions ago :(

**Comment by classilla** [comment]
Probably not trivially because I suspect much of the underlying structs have changed.

**Comment by barracuda156** [comment]
> Probably not trivially because I suspect much of the underlying structs have changed.

And there is no known way to emulate VSX on Apple Altivec, right?

**Comment by classilla** [comment]
Not in any efficient way. VSX basically uses (and expands) FPRs. Any equivalent code without it would be larger and much slower.
