### ISSUE TITLE
Window freezes and loses focus on high load

### ISSUE THREAD

**Issue by l1k** [classilla/tenfourfox#332]
There's a regression in 45.4.0 as well as  45.5.0b2 that's not been present on 38: Occassionally the browser window seemingly no longer accepts key presses or mouse clicks and the window contents essentially freeze.

Curiously, key presses and mouse clicks are still being processed, their effect is just no longer visible: E.g. if one tab was open before the window froze and I click on the button to add a new tab, seemingly nothing happens. But when I subsequently close the window by clicking on the window decoration button, a popup appears warning me that _two_ tabs are open. The three window decoration buttons on the top left are the only UI elements that still work at that point. Closing and reopening the window doesn't make the issue go away, I have to quit and restart the browser.

It's a bit unclear what triggers the bug but I've noticed that if I open an https URL in parallel with Safari, the machine gets fairly sluggish (apparently due to the OCSP check) and often TenFourFox freezes on that occasion. This is a relatively slow machine (550 MHz 7410). Interestingly, if I switch to another application and then back to TenFourFox, the scroll bar stays light gray, whereas normally it should become dark gray. I'm using the Graphite theme rather than the Aqua theme on 10.4, and light gray indicates that the window doesn't have focus.

**Comment by l1k** [comment]
Shoot! I had missed the pointer to Tenderapp in the README. Apologies, feel free to close.

This seems to be a race condition so providing a reliable reproducer will be difficult. It happens intermittently, though fairly frequently. Originally I thought it's caused by switching between applications while a page is loading in TenFourFox, but yesterday it occurred without switching, just with Safari loading a separate page in the background. Hence my suspicion that it's triggered by high CPU load. There's [another report](http://tenfourfox.tenderapp.com/discussions/problems/8219-latest-release-45x) of freezes with 45 on Tenderapp which might be related. I'll see if I can narrow the issue down further. Thanks.

**Comment by l1k** [comment]
It seems to be an issue with Keychain integration. The reproducer is:
* Open Keychain, open its Preferences, in the Certificates pane select "Best Effort" for both OCSP and CRL.
* Open TenFourFox 45, open some arbitrary website. (I've only tested it with one using https.)
* Open Safari, open an https URL. Safari must be either newly started or the URL must be one you haven't visited during this session because the OCSP/CRL status is cached, so the bug isn't triggered if you open an https URL you've already visited.
* Switch to TenFourFox, the window should be frozen and have lost focus.

If you select "Off" for OCSP and CRL in Keychain, the issue doesn't occur. But that's not recommendable for security reasons.

**Comment by l1k** [comment]
Did some more tests and for some reason had trouble reproducing the issue if the website that was opened in TenFourFox was GitHub. But opening [this one](https://steveblank.com/2016/10/24/why-tim-cook-is-steve-ballmer-and-why-he-still-has-his-job-at-apple/) in TenFourFox and [this one](https://t.co/TkXWzDwhne) in Safari triggers the bug reliably for me.

**Comment by classilla** [comment]
I can't reproduce this on any of my machines. There is a spike of CPU activity but everything resumes. The 500MHz G4 has a pause, but otherwise recovers as well. I tried it with a couple arbitrary sites as well as the two you specified.

If you have other steps I can try, please post, but otherwise it might be better to put this on Tenderapp where others can compare notes. Clearly the test systems here don't have the same configuration as yours and I'd like to limit what's here to what I've actually confirmed, can reproduce, and intend to fix. Again, nothing personal.
