### ISSUE TITLE
New Hot NSS (and New Hot NSPR)

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#369]
Update to the NSS in ESR52 to allow easier backporting of fixes and pick up new ciphers.

**Comment by classilla** [comment]
We will also need an NSPR update.

Current plan:
To a clean 45 tree (before landing the TenFourFox patches on top), copy over `nsprpub/` and `security/` (_except_ `manager` because this has some other changes that may not be compatible, so go only with the others) from ESR52. 

We should not enable TLS 1.3 yet; see https://bugzilla.mozilla.org/show_bug.cgi?id=1342082 and https://bugzilla.mozilla.org/show_bug.cgi?id=1310516 . Also, we would probably need to copy in and merge the changes from the manager to get that functional too.

Best if we do this as a cycle on its own since there are lots of possibilities for regressions here and we don't really have tests for this.

**Comment by classilla** [comment]
Actually, let's do NSPR for FPR1. `security/` has minor changes needed for TenFourFox:

`security/sandbox/mac/Sandbox.mm`
`security/nss/coreconf/Werror.mk`
`security/pkix/lib/pkixnames.cpp`
`security/manager/ssl/RootCertificateTelemetryUtils.cpp`

These can be picked up post-facto -- we can just dump the files from ESR52 into `security/` and then redo the patches. NSPR is harder, so we'll do that for the FPR uplift, since it should be a very safe update.

**Comment by classilla** [comment]
NSPR 4.13.1 landed in "FPR0" and builds.

**Comment by classilla** [comment]
See also PM1057.

**Comment by classilla** [comment]
This will be needed to fix #576 because of the added cipher requirement, so let's get 'er done.

**Comment by roytam1** [comment]
New NSS uses SQLite for its databases instead of legacy `dbm`, you may check if there is performance issue because of that, or keep using dbm:
https://github.com/roytam1/mozilla45esr/commit/c5a8d2ab4709c114a78038adf4667baf1315fce4

**Comment by classilla** [comment]
This is sticking.
