### ISSUE TITLE
Reduce the impact of sessionstore updates

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#444]
I'm unwilling to increase the interval substantially over the 25 second interval used now for session store writes (especially since this is over the Firefox default of 15), but we've reduced the size of them before by cutting down on the maximum window and tab undos, so I think we should now concentrate on history.

Proposal: reduce `browser.sessionstore.max_serialize_back` and `browser.sessionstore.max_serialize_forward` to 5 each (currently 10 and -1, i.e., no limit) for FPR5.

**Comment by classilla** [comment]
See also https://wiki.mozilla.org/Firefox/session_restore

We could also cut down `browser.sessionstore.cleanup.forget_closed_after`. That value is quite high.

Finally, there are probably some opportunities to pare down the JS in `browser/components/sessionstore/SessionStore.jsm` also.

**Comment by classilla** [comment]
Cut to 60 seconds. This is about as far as I'm willing to go.

**Comment by nemanjacosovic** [comment]
I think this is a good call.
