### ISSUE TITLE
Update ICU timezone

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#447]
Spun off from #443. We need to get `intl/icu/source/tools/tzcode/tz2icu.cpp` compiled and then work off the 2017 timezone file. See https://bugzilla.mozilla.org/show_bug.cgi?id=1411957

**Comment by classilla** [comment]
Now up to 2018c. https://bugzilla.mozilla.org/show_bug.cgi?id=1430761

**Comment by roytam1** [comment]
ICU posted their own converted versions.
http://bugs.icu-project.org/trac/browser/data/trunk/tzdata/icunew/2018e/44

FYI: https://github.com/roytam1/mozilla45esr/commit/d8d387c8afd6ba1b4e0029b69a5f21919dccdeb2

**Comment by classilla** [comment]
Handy, thanks. That can go in FPR9.
