### ISSUE TITLE
which version for 10.5.6 Intel ?

### ISSUE THREAD

**Issue by mrkapqa** [classilla/tenfourfox#456]
Hello ,

on an Imac i use i am affected by a softwae bug that doesnt allow me to upgrade to snow leopard and above,
so i'd stay on leopard 10.5.6 or 10.5.8 -
is there a Intel Version that i can install of TenFourFox to enable smooth browsing?

Thank you so much for yor dedicated support.

**Comment by classilla** [comment]
Please don't post end user requests to Github. This is a worklist, not a support area. For end-user support questions, see Tenderapp: http://tenfourfox.tenderapp.com/

There is no currently supported version of TenFourFox for Intel. Some users have had some success getting the G3 version to run, but you may need to take special steps for that. Even if it works, however, it is officially an unsupported configuration. See the FAQ: https://github.com/classilla/tenfourfox/wiki/AAATheFAQ#can-104fx-run-on-an-intel-mac-with-104-105-or-106

**Comment by rmottola** [comment]
In the meanwhile, we are further on that... and there are Intel binaries - without any guarantee. And thanks to @kencu soon in MacPorts too!
