### ISSUE TITLE
Updating the release year

### ISSUE THREAD

**Issue by polluks** [classilla/tenfourfox#460]
https://github.com/classilla/tenfourfox/blob/c9b2922b70d0052b78a1a9bc6069cefe5a119124/browser/locales/en-US/chrome/browser/aboutDialog.dtd#L52
The German locale even says "2016"...

**Comment by classilla** [comment]
Thanks. Repaired in most recent langpacks in issue 42.

**Comment by classilla** [comment]
Mainline will be fixed in FPR5.
