### ISSUE TITLE
TenFourFoxInstaller: can't bootstrap TenFourFox on 10.4 or 10.5 with Safari

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#476]
Rather than host on plain HTTP, which would be expensive and delay the inevitable, we could create a Downloader app containing ntools `curl`, current certificates and a script.

The script would ask Floodgap for the current version and determine the system architecture to construct the SourceForge download URL. It would then iterate through until it got the mirror link and start downloading.

Platypus should be sufficient for this as the front end. We just need to hack `curl` a little so that it emits `PROGRESS:` indicators.

**Comment by classilla** [comment]
@nemanjacosovic Whoa, so you're saying Leopard is also affected?

**Comment by chris-chtrusch** [comment]
Safari 5 with Leopard Webkit has no problem with SourceForge, but bare Safari 5.0.6 was last updated in mid-2013, so it can't connect. The problem is that Leopard Webkit must also be downloaded on SourceForge. Maybe have a look at how Tobias got around this problem?

**Comment by classilla** [comment]
@internetzel Tobias, want to comment?

**Comment by internetzel** [comment]
I didn't notice that problem yet.
Leopard WebKit supports TLS 1.1 and 1.2, elliptic curves and SHA-2 signature algorithms by means of an updated Security framework - all of which are missing on OS X up until 10.5, with 10.6 until 10.8 only adding support for elliptic curves (so even those OS X versions might be unable to download via HTTPS).
If not being hosted on a private server I think it might even become impossible to download anything using a stock install without having a capable application ready on some external media...

**Comment by classilla** [comment]
Well, I'm working up the installer now. I have a stripped-down `cURL` linked against OpenSSL 1.0.2 that can download files from SourceForge and I'm teaching it how to emit Platypus-compatible progress markers. Next will be to get it to automatically get the current version.

I can host downloaders of reasonable size on Floodgap's unencrypted HTTP. @internetzel , I'll do the same for you as a public service if you like. I have to see how much this will take up; obviously I would like to pare it down as much as possible since I host off a T1. The bare minimum, stripped `cURL` binary is about 2MB uncompressed and I'm going to see if I can get that smaller.

**Comment by internetzel** [comment]
Thanks for the offer!
But I guess anyone who uses Leopard WebKit (which itself isn't a browser, not even an independent application) does also have TenFourFox installed - so I think a TFF installer would be convenient for getting Leopard WebKit.

**Comment by classilla** [comment]
For those interested in testing it out, here is a first cut. It seems to work properly on my 10.4 and 10.5 systems. It automatically determines the machine type and current version and downloads the browser directly from SourceForge.

[TenFourFoxDownloader.dmg.zip](https://github.com/classilla/tenfourfox/files/1738849/TenFourFoxDownloader.dmg.zip)

**Comment by classilla** [comment]
The installer is live. Use the offered one on the main page since there were a couple last-minute edge case fixes.
