### ISSUE TITLE
Add support for ECDHE with X25519

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#481]
https://bugzilla.mozilla.org/show_bug.cgi?id=957105

This is in ESR52, so if we just upgrade to 3.28 ...

**Comment by roytam1** [comment]
If you upgrade NSS/NSPR, TLS 1.3 is do-able as well. (just don't know if new NSS/NSPR will work well on 10.4 or not, I did that in my 45esr SSE win32 fork works quite well)
For your reference: https://github.com/roytam1/mozilla45esr/compare/090424912048ad68e611830cf68d43caf42e6efc...c1a1aa34dda5965a64ba0548f8a97bb528e82881

**Comment by classilla** [comment]
Superseded by New NSS (#369).
