### ISSUE TITLE
Be very, very evil with async/await

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#490]
It would be perfectly syntactically acceptable, just evil, to make `async` and `await` into null keywords (at the parser level, where they are simply eliminated). This would have the effect of making them synchronous, and defeating their purpose, but would allow scripts that use them to run without having to add all the machinery.

**Comment by classilla** [comment]
(naturally this would not include the subtlety of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction )

**Comment by roytam1** [comment]
is it possible to make a null/no-op keyword?
if not, we may aliasing async/await to new?

**Comment by classilla** [comment]
This might fix the issue with https://vsco.co/feed which has an ES6 `Promise` implementation relying on it, though I'm not entirely certain.

**Comment by classilla** [comment]
After review of the spec, I've determined this can't succeed without side effects, since `async` isn't actually a reserved word and `await` is only a keyword within an `async` function. Since we'd have to implement a substantial amount of changes to the parser, that defeats the purpose of making this a cheap implementation. Diff here for the record.

[await.txt](https://github.com/classilla/tenfourfox/files/2377880/await.txt)
