### ISSUE TITLE
WebP support?

### ISSUE THREAD

**Issue by roytam1** [classilla/tenfourfox#501]
I've just finished porting their somewhat old webp patch to firefox45. I wonder if you're interested in it?
https://github.com/roytam1/mozilla45esr/compare/5a93166...6d3f89033

**Comment by kencu** [comment]
very cool. FWIW, I note there is a version 1.0.0 of webp currently in MacPorts that builds through to completion with gcc48 without any trouble on 10.4 PPC. I believe there is also a toggle here to use the system webp. Perhaps that might make the situation easier to maintain?

**Comment by PowerOlive** [comment]
great

**Comment by classilla** [comment]
Initial support is shipping in FPR13b1.

**Comment by classilla** [comment]
Closing since basic support is sticking. When I have a solution in mind for animated WebP, we'll open a separate issue.
