### ISSUE TITLE
Altivec gcc switches

### ISSUE THREAD

**Issue by NapalmSauce** [classilla/tenfourfox#503]
I randomly stumbled upon this (note this is on Leopard as I don't have access to a Tiger machine for now):

```
G4:~ user$ gcc-mp-4.8 -flax-vector-conversions -O3 -mcpu=7450 -mtune=7450 -falign-loops=16 -falign-functions=16 -falign-labels=16 -falign-jumps=16 -read_only_relocs suppress -mdynamic-no-pic -Q --help=target | grep altivec
 -mabi=altivec               		[disabled]
 -mabi=no-altivec            		[enabled]
 -maltivec                   		[disabled]
 -maltivec=be                		[disabled]
 -maltivec=le                		[disabled]
 -mwarn-altivec-long         		[enabled]

```
Obviously that line came from G4-7450.mozcfg.
This is the same with gcc 5 and 6,  but 7 switches -maltivec on.-mcpu=G5/970 does as 7450 with the above options.

If I get it correctly, this disables SIMD generation except for codepaths that explicitly enable it.

So I'm opening this issue as I previously assumed -mcpu=[G4 or G5 string] would always enable -maltivec on darwin with these versions of gcc.

Can you confirm (or correct me if necessary)?

**Comment by classilla** [comment]
I don't think `--help=target` is doing what you think it is. For example, if you look down later in the list, you'll see

```
  -mvsx-scalar-double                   [enabled]
```

There's no VSX support on any Power Mac. I don't believe the help option takes `--mcpu` into account. This stackoverflow answer implies that some changes were made in `gcc` 7 which would explain what you're seeing: https://stackoverflow.com/questions/5470257/how-to-see-which-flags-march-native-will-activate#comment75783920_5470379

Furthermore, AltiVec code generation must be taking place, or we wouldn't have had #461.

**Comment by NapalmSauce** [comment]
I don't have anything to refute that last remark.
Well, it's no news that how an options _actually_ influences the backend of a huge compiler such as gcc easily gets confusing.

I often prefer redundant flags for that reason.
