### ISSUE TITLE
104fx_copy can get confusing

### ISSUE THREAD

**Issue by NapalmSauce** [classilla/tenfourfox#514]
When I use the script more than once and point at the same location everytime, e.g `/users/myname/TenFourFox.app`  the first application bundle will be stuffed with the second one at `/users/myname/TenFourFox.app/TenFourFox.app`, since this is the normal behaviour of unix directories.

Can something like temporarily staging a copy of the .app on top of the tree to relink libraries then create an archive with `tar -cf`  instead to get an overwrite behaviour be acceptable? I think it would avoid somewhat misleading cases that involve the above.

**Comment by classilla** [comment]
So are you saying you want it to overwrite any existing browser at that path? I could just throw in an `rm -rf $where` or something.

**Comment by NapalmSauce** [comment]
Seriously. How can I miss this. Yeah, exactly what I mean. Thanks for the tip.

**Comment by NapalmSauce** [comment]
I'm not doing it on purpose, but can you enclose `rm -rf` like this?
```
if (-e ${ppath}/contents/macos/firefox) then
rm -rf ${ppath} 
endif
```
So it absolutely avoids overwriting an unrelated directory, expecting it would produce `${ppath}/TenFourFox.app`

**Comment by classilla** [comment]
OK.
