### ISSUE TITLE
async/await, this time with feeling [M1185106]

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#521]
A number of broken sites rely on this functionality, and it just made it into Fx52. I'm not 100% sure it's doable, but reviewing the changesets suggest that much of it should work sans the Annex B portions.

https://bugzilla.mozilla.org/show_bug.cgi?id=1185106
(note deps)

**Comment by classilla** [comment]
We need to implement JS `Promise`s :/

**Comment by classilla** [comment]
The C++ version used here seems to originate from https://hg.mozilla.org/mozilla-central/rev/309ecb16acfe ( https://bugzilla.mozilla.org/show_bug.cgi?id=1313049 )

However, the root implementation it descends from is here: https://bugzilla.mozilla.org/show_bug.cgi?id=911216
That is a nightmare.

**Comment by classilla** [comment]
https://bug911216.bmoattachments.org/attachment.cgi?id=8727872 contains the base implementation plus some tests. We could ignore all the `builtin/Promise.*` stuff and just use the ones from 52ESR. The `jsapi.*` changes would generally apply with the differences in `InvokeArgs` and this version does implement `js::CallSelfHostedFunction` for us.

However, the changes in `vm/SelfHosting.cpp` are different from what is in ESR52. This would be a very big merge job.

**Comment by classilla** [comment]
Aborting the current parser work while I think this over. The other patches should be webcompatible.
[aborted_521.txt](https://github.com/classilla/tenfourfox/files/2386277/aborted_521.txt)

**Comment by roytam1** [comment]
wonder if older round of async/await patches can be used and fix for final spec? https://hg.mozilla.org/mozilla-central/rev/2384726c541f

**Comment by classilla** [comment]
That's an interesting idea. It's of the right era. I'm not sure what the test failures are, but it's worth a shot.

**Comment by classilla** [comment]
It builds and passes most tests but I have some serious doubts about whether it will work properly in the browser mostly due to its hal-fassed `Promise` implementation. It fails these tests, but largely as a consequence of its shell implementation.

```
## js1_5/GC/regress-319980-01.js: rc = 3, run time = 0.669532
BUGNUMBER: 319980
STATUS: GC not called during non-fatal out of memory
This test should never fail explicitly. You must view the memory usage during the test. This test fails if memory usage for each subtest grows
js1_5/GC/regress-319980-01.js:39:3 TypeError: Intervals other than 0 are not supported
Stack:
  @js1_5/GC/regress-319980-01.js:39:3
REGRESSION - js1_5/GC/regress-319980-01.js
[ 4392|    1|    0|  228]  32% ===========>                           |6450.2s
## js1_5/GC/regress-319980-01.js: rc = 3, run time = 0.933304
BUGNUMBER: 319980
STATUS: GC not called during non-fatal out of memory
This test should never fail explicitly. You must view the memory usage during the test. This test fails if memory usage for each subtest grows
js1_5/GC/regress-319980-01.js:39:3 TypeError: Intervals other than 0 are not supported
Stack:
  @js1_5/GC/regress-319980-01.js:39:3
REGRESSION - js1_5/GC/regress-319980-01.js
[ 4669|    2|    0|  254]  34% ============>                          |6641.3s
## js1_5/Regress/regress-314401.js: rc = 3, run time = 0.649189
BUGNUMBER: 314401
STATUS: setTimeout(eval,0,"",null)|setTimeout(Script,0,"",null) should not crash
js1_5/Regress/regress-314401.js:23:3 ReferenceError: window is not defined
Stack:
  @js1_5/Regress/regress-314401.js:23:3
REGRESSION - js1_5/Regress/regress-314401.js
[ 4670|    3|    0|  254]  34% ============>                          |6642.3s
## js1_5/Regress/regress-314401.js: rc = 3, run time = 0.95136
BUGNUMBER: 314401
STATUS: setTimeout(eval,0,"",null)|setTimeout(Script,0,"",null) should not crash
js1_5/Regress/regress-314401.js:23:3 ReferenceError: window is not defined
Stack:
  @js1_5/Regress/regress-314401.js:23:3
REGRESSION - js1_5/Regress/regress-314401.js
[12990|    4|    0| 1098] 100% ======================================>|15033.8s
REGRESSIONS
    --baseline-eager js1_5/GC/regress-319980-01.js
    --ion-eager --ion-offthread-compile=off js1_5/GC/regress-319980-01.js
    --baseline-eager js1_5/Regress/regress-314401.js
    --ion-eager --ion-offthread-compile=off js1_5/Regress/regress-314401.js
FAIL
```

Next step is add a couple more tests from `esr52` and then see if it actually works right in the browser with DOM `Promise`s.

**Comment by classilla** [comment]
It doesn't spin the event loop properly, so sites relying on it don't work right. However, many sites that didn't load at all now at least parse, and some load further. Github now enables a couple more buttons. With #541 also loaded, the site is now complaining about supporting `await async` which is permitted by the spec and not addressed by the patch above, and it also doesn't like `()=>{!async function(){ ... }`.

**Comment by classilla** [comment]
I've concluded I can't get the syntactic changes to work with this version. Backing out and putting the work here for reference.
[issue521-failed-again.txt](https://github.com/classilla/tenfourfox/files/3292676/issue521-failed-again.txt)
