### ISSUE TITLE
Python codebase status

### ISSUE THREAD

**Issue by lyssdod** [classilla/tenfourfox#545]
Hi,

It seems that `python` directory contains all packages which can be installed from pypi during the build step, so they are not really needed to stay in the repo. Also, this might fix https://github.com/classilla/tenfourfox/issues/202, since psutil package has been updated since.

**Comment by thecraftman** [comment]
Hey, good day i am having isuues with my pypi

**Comment by lyssdod** [comment]
What are they?

**Comment by classilla** [comment]
I'd rather keep them at the same version they're at, since builders may not have access to them in the future if their minimum versions are beyond what's provided for PowerPC Mac OS X.
