### ISSUE TITLE
Font Blacklist

### ISSUE THREAD

**Issue by chris-chtrusch** [classilla/tenfourfox#560]
Please consider these for the font blacklist:

https://www.heise.de/sso/fonts/SourceSansPro-Regular.otf.woff2
https://www.heise.de/sso/fonts/SourceSansPro-Semibold.otf.woff2
https://www.vetmed.fu-berlin.de/assets/default2/NexusSansWeb-Pro.woff
https://www.vetmed.fu-berlin.de/assets/default2/NexusSansWeb-Pro-Bold.woff

**Comment by classilla** [comment]
I'll add to FPR15 final (the beta is already being built).

**Comment by classilla** [comment]
Never mind, the beta will be held because we're vulnerable to M1544386 :((

**Comment by classilla** [comment]
done
