### ISSUE TITLE
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 inappropriately selected (regression from #489)

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#576]
A la #489, add support for `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384` (now required for SourceForge). This is blocking updates. The Downloader works fine.

**Comment by classilla** [comment]
Also, we should have some sort of message to indicate that a cipher mismatch seems to have occurred, even if just in DEBUG.

**Comment by classilla** [comment]
Alternatively, we could implement one of these (or all, just in case):

```

TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)                                                                                    ECDH secp256r1 (eq. 3072 bits RSA)   FS | 256
-- | --
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (0xc024)                                                               ECDH secp256r1 (eq. 3072 bits RSA)   FS                                                       WEAK | 256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)                                                               ECDH secp256r1 (eq. 3072 bits RSA)   FS                                                       WEAK | 256
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)                                                                                    ECDH secp256r1 (eq. 3072 bits RSA)   FS | 128
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023)                                                               ECDH secp256r1 (eq. 3072 bits RSA)   FS                                                       WEAK | 128
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)                                                               ECDH secp256r1 (eq. 3072 bits RSA)   FS                                                       WEAK | 128
 

```

We should be able to use the `AES_256_GCM_SHA384` support we did in #480 here.

**Comment by classilla** [comment]
With the environment variables `SSLDEBUG` set to 1 and `SSLTRACE` set to 64 in a debug build we can see that SourceForge fails to negotiate false start (the callback returns `FALSE`).

In Fx70 on the Talos, if I disable this cipher and only this cipher, I get an inadequate security error. We can add a warning about false start, at least for debug builds; it would give us an idea for future problems.

**Comment by classilla** [comment]
Someone discovered that `network.http.spdy.enforce-tls-profile` to `false` fixes this. In `Http2Session::ConfirmTLSProfile()` if `EnforceHttp2TlsProfile()` is true, it requires TLS 1.2, DH 2048 bit or ECDH 224 bit (and only DH or ECDH), and an AEAD cipher. This could still be a cipher issue, but now we can at least instrument to see what check is failing. The false start is probably a symptom of that. It may well be that instead of not supporting the right cipher we're negotiating the wrong one.

**Comment by classilla** [comment]
See also https://hg.mozilla.org/integration/mozilla-inbound/rev/361ac226da2a (which was in 45.6.1 as well as 51).

**Comment by yuhong** [comment]
Now uses NIST P-256. Using P-224 was probably not a good idea as it is not twist secure.

**Comment by classilla** [comment]
New test URL: https://www.culttvmanshop.com/HAL9000-11-scale-kit-from-Moebius-Models_p_4785.html

**Comment by classilla** [comment]
This site prefers TLS 1.3. When limited to 1.2, on Fx72 on the Talos, it negotiates TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.

**Comment by classilla** [comment]
With

```
NSPR_LOG_MODULES nsHttp:5
NSPR_LOG_FILE http.log
```

```
42199040[63b920]: Http2Session::ConfirmTLSProfile 39390400 mConnection=2528510
42199040[63b920]: nsHttpConnection::GetSecurityInfo trans=39390400 tlsfilter=0 socket=3f6ddbe0
42199040[63b920]: Http2Session::ConfirmTLSProfile 39390400 sslsocketcontrol=37675630
42199040[63b920]: Http2Session::ConfirmTLSProfile 39390400 version=303
42199040[63b920]: Http2Session::ConfirmTLSProfile 39390400 MAC Algortihm (aead==6) 5
42199040[63b920]: Http2Session::ConfirmTLSProfile 39390400 FAILED due to lack of AEAD
```

**Comment by classilla** [comment]
The reason seems to be some weirdness about preference. The server's preferences are

# TLS 1.2 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)   ECDH x25519 (eq. 3072 bits RSA)   FS   WEAK 	256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)   ECDH x25519 (eq. 3072 bits RSA)   FS   WEAK 	128
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   ECDH x25519 (eq. 3072 bits RSA)   FS 	128

We do have `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)` and we even list it preferentially but it is not being selected. Perhaps a better idea is not to advertise the CBC ciphers.

**Comment by classilla** [comment]
Yet, Fx72 has it right. When capped to TLS 1.2, Qualys says

```
Cipher Suites (in order of preference)
--
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b) 							   			Forward Secrecy | 128
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f) 							   			Forward Secrecy | 128
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9) 							   			Forward Secrecy | 256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8) 							   			Forward Secrecy | 256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c) 							   			Forward Secrecy | 256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030) 							   			Forward Secrecy | 256
```

and the right one is selected. Maybe we add some hard preference for GCM over CBC, since it does advertise CBC, and GCM is still selected.

**Comment by classilla** [comment]
This is actually a regression from #489. `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256` was never part of Firefox originally and we have a typo in the security manager.

**Comment by classilla** [comment]
This is actually a regression from #489. When `security.ssl3.ecdhe_rsa_aes_128_sha256` is set to `false` the site negotiates the correct cipher. This cipher was never originally part of Firefox (we just turned it on in NSS as a quick fix), so this is our bug.

We could maybe blacklist it for SPDY connections, since Amtrak still works (isn't SPDY).

**Comment by classilla** [comment]
Or, we find some way to implement Poly1305 and ChaCha, and get rid of this cipher. Maybe this is where we update NSS.

**Comment by classilla** [comment]
Fixed by New NSS.

**Comment by roytam1** [comment]
> we find some way to implement Poly1305 and ChaCha

although you chose updating NSPR and NSS, it seems that ChaCha20-Poly1305 is able to port to NSS 3.21.4 (at least on i386) for reference:
https://github.com/roytam1/RetroZilla/commit/db2c36920504e182562d3f4a4423e1e188c939c0
