### ISSUE TITLE
Disturbing keylogger malware in this software

### ISSUE THREAD

**Issue by ayumi-cloud** [classilla/tenfourfox#598]
The following website, has your software for downloading found here: https://mac.filehorse.com/download-tenfourfox/

When running it through virustotal, we see the following results: https://www.virustotal.com/gui/file/7f238a7cf7182a6e312154d926f053a14f8d58c7d9a0ea81418f1c43b8af8585/detection

Note the `PUA.OSX.KeyLogger` result which is a Mac keylogger script.

I leave the admins to sort this out.

**Comment by classilla** [comment]
This is a known false positive which has occurred in multiple versions, and they don't care, so neither do I. Use it or don't.
