### ISSUE TITLE
Possible to get a working SpiderMonkey js shell from tenfourfox sources?

### ISSUE THREAD

**Issue by cellularmitosis** [classilla/tenfourfox#606]
First, thanks so much for working on tenfourfox!

I was wondering if it is possible to build the spidermonkey js repl shell from tenfourfox sources?

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Introduction_to_the_JavaScript_shell

Thanks!

**Comment by classilla** [comment]
Not only is it possible, but every copy of TenFourFox has one:

```
bruce:/Applications/TenFourFoxG5.app/% ./Contents/MacOS/js
js> print("hello world");
hello world
js> 
```

It is fully JIT-enabled, and I use it as part of the self-test battery, so it is verified and supported (in fact, probably has the best test coverage of anything in TenFourFox).

**Comment by cellularmitosis** [comment]
Awesome, thanks!
