### ISSUE TITLE
Javascript menu item

### ISSUE THREAD

**Issue by NapalmSauce** [classilla/tenfourfox#623]
A UI (menu) item that flips and reflects 'javascript.enabled'. It's useful to save the CPU time spent in scripts when unneeded, and in firefox it's either available from add-ons or buried in about:config. 

Could a javascript toggle be added as a built-in functionality? I've made a patch for a menu item that mostly reproduces the code for View > Zoom > Zoom Text Only.

It adds a localizable string, so I can understand if you don't want it or hold it until a new langpack is planned..

**Comment by classilla** [comment]
I'm not opposed, though so we don't take up @chris-chtrusch 's time unnecessarily, we should batch any other localization updates at the same time. I'm thinking of a couple for reader view and possibly one around user agents by domain, in case I want to expand these.

**Comment by chris-chtrusch** [comment]
I'm not opposed to that, either. In the meantime, there is a classic extension for that (quickjs) which I've been using for years. I pulled the xpi from my local copy of legacycollector.org and uploaded it to our extensions archive at https://sourceforge.net/projects/tenfourfox/files/addons/archive/

**Comment by NapalmSauce** [comment]
Yes, thank you, that's one more reason there's no hurry, and I have no problem with rebasing my pulls for a while.

With the attached diff it looks like this:
![tools](https://user-images.githubusercontent.com/35426980/93923556-89534b80-fce1-11ea-83d3-9fe955a5edc9.gif)

Feel free to comment or ask for changes.

[diff.txt](https://github.com/classilla/tenfourfox/files/5263376/diff.txt)

**Comment by classilla** [comment]
This seems fine to me, except it should be JavaScript (camel case). I'll take a PR with that. @chris-chtrusch , any objections? It looks like it's a single string and we might be able to source it for the other less typical languages from other locale strings.

**Comment by chris-chtrusch** [comment]
No problem, this functionality used to be in FF 3.6 (but in Preferences > Content) with the exact same wording, I can source all translations from there.

**Comment by NapalmSauce** [comment]
Thanks! PR is set up. Chris, if there's something I can do to spare you trouble (dump the 'Enable JavaScript' string from firefox 3.6 localizations in a text file maybe?) you can ask, after all this is my fault.

**Comment by chris-chtrusch** [comment]
Don't worry, it's not a big deal. I wasn't happy when Mozilla removed the UI for toggling JS and expected us to install yet another add-on to restore it; I'm glad it's back.

**Comment by classilla** [comment]
Merged.

**Comment by classilla** [comment]
This has landed and stuck.
