### ISSUE TITLE
Would like webrequest api to be added.

### ISSUE THREAD

**Issue by R3n001** [classilla/tenfourfox#634]
I have some WebExtensions I would like to be able to use, but they use webrequest, so they don't work.

**Comment by classilla** [comment]
You didn't read the readme, did you? This is a worklist, not a support area.

**Comment by R3n001** [comment]
> 
> 
> You didn't read the readme, did you? This is a worklist, not a support area.

I don't need support, I've found something that doesn't work because of a missing feature, so I'm requesting the feature.
