### ISSUE TITLE
Copy Current Location Functionality  Takes Very Long To Update In TenFourFoxBoxes

### ISSUE THREAD

**Issue by alex-free** [classilla/tenfourfox#635]
I have been working on an AppleScript application which uses the “Copy Current Location” functionality automatically in AppleScript by simulating the keyboard shortcut combo. Unfortunately I have to wait quite a while until essentially the entire page is done loading before the URL obtained in this way is available. 

Is there any way to update the current URL faster?

**Comment by classilla** [comment]
Not currently, no. If you have a patch for this, I'll consider it.
