### ISSUE TITLE
Cannot access if port number is larger than 32767

### ISSUE THREAD

**Issue by roytam1** [classilla/tenfourfox#650]
I posted a solution in https://github.com/classilla/tenfourfox/commit/4f70dd5c954cfcfd55357527da98c15f8355fbe5#r59478686

of course I can create a PR if there is a need.

screenshot:
![image](https://user-images.githubusercontent.com/1192577/140958278-46810a59-a985-4d5f-8586-db99a5f51fc9.png)

**Comment by classilla** [comment]
Thanks.
