### ISSUE TITLE
zip error: Not supported (uzoff_t not same size as zoff_t)

### ISSUE THREAD

**Issue by barracuda156** [classilla/tenfourfox#652]
I am getting these weird errors when compiling browser/experiments and toolkit/components. Never encountered anything like this before.
What could be the reason?

**Comment by classilla** [comment]
I don't know. I need a little more context than that.

**Comment by barracuda156** [comment]
@classilla This is the part where the build fails:

gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/browser/components'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/browser/components'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/browser/experiments'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/browser/experiments'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/browser/fuel'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/browser/fuel'
Exporting extension to source/test/addons/translators.xpi.
Exporting extension to source/test/addons/unpacked.xpi.
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/browser/modules'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/browser/modules'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/dom/media/webvtt'
Exporting extension to source/test/addons/unsafe-content-script.xpi.
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/dom/media/webvtt'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/dom/presentation/provider'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/dom/presentation/provider'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/addoncompat'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/addoncompat'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/asyncshutdown'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/addon-sdk'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/console'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/asyncshutdown'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/contentprefs'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/console'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/crashmonitor'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/contentprefs'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/crashmonitor'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/downloads'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/formautofill'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/downloads'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/formautofill'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/jsdownloads/src'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/passwordmgr'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/jsdownloads/src'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/passwordmgr'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/privatebrowsing'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/places'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/privatebrowsing'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/processsingleton'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/processsingleton'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/prompts/src'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/places'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/remotebrowserutils'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/prompts/src'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/telemetry'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/remotebrowserutils'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/thumbnails'
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/thumbnails'
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/timermanager'

zip error: Not supported (uzoff_t not same size as zoff_t)

zip error: Not supported (uzoff_t not same size as zoff_t)

zip error: Not supported (uzoff_t not same size as zoff_t)

zip error: Not supported (uzoff_t not same size as zoff_t)

zip error: Not supported (uzoff_t not same size as zoff_t)
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/timermanager'

zip error: Not supported (uzoff_t not same size as zoff_t)
gmake[5]: Entering directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/utils'

zip error: Not supported (uzoff_t not same size as zoff_t)

zip error: Not supported (uzoff_t not same size as zoff_t)
gmake[5]: *** [Makefile:28: misc] Error 19
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/telemetry'
gmake[4]: *** [/Users/svacchanda/tenfourfox/config/recurse.mk:79: toolkit/components/telemetry/misc] Error 2
gmake[4]: *** Waiting for unfinished jobs....
gmake[5]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg/toolkit/components/utils'
gmake[4]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg'
gmake[3]: *** [/Users/svacchanda/tenfourfox/config/recurse.mk:33: misc] Error 2
gmake[3]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg'
gmake[2]: *** [/Users/svacchanda/tenfourfox/config/rules.mk:547: default] Error 2
gmake[2]: Leaving directory '/Users/svacchanda/tenfourfox/obj-ff-dbg'
gmake[1]: *** [/Users/svacchanda/tenfourfox/client.mk:396: realbuild] Error 2
gmake[1]: Leaving directory '/Users/svacchanda/tenfourfox'
gmake: *** [client.mk:171: build] Error 2
36-9:tenfourfox svacchanda$

**Comment by classilla** [comment]
I've never seen this. I think it has something to do with how your `zip` (MacPorts?) is compiled. If `off_t` isn't the same size as an `unsigned long long` then this message will turn up. See https://github.com/cysin/info-zip/blob/master/tailor.h#L137 and https://github.com/cysin/info-zip/blob/master/zip.c#L2491 . I don't think this is a TenFourFox build system bug. You should verify in the configure output what `zip` binary is being used.

**Comment by classilla** [comment]
Closing as unreproducible. If this is consistently observed, please repost.

**Comment by barracuda156** [comment]
> Closing as unreproducible. If this is consistently observed, please repost.

@classilla Yes, I will check it soon. Been busy with other projects.
