### ISSUE TITLE
Not working on OSX 10.4.7, says wrong OS version. iBook G4 (7450).

### ISSUE THREAD

**Issue by vorob1** [classilla/tenfourfox#656]
I've got iBook G4, I've downloaded latest 7450 release and it says wrong OS. No idea what to do :(

![photo_2022-08-16_01-11-16](https://user-images.githubusercontent.com/36692361/184730856-4a2ffb27-a1aa-4e45-beeb-a486da513262.jpg)

![photo_2022-08-16_01-19-25](https://user-images.githubusercontent.com/36692361/184730862-c894121d-fa39-49ef-8947-b517a26b5212.jpg)

**Comment by classilla** [comment]
This is not for user support - this is a worklist.

In answer to your question, you need at least 10.4.9 (preferably 10.4.11). You should download the combo updater from Apple and install it, and TenFourFox should start. If you have other questions, please post them to Tenderapp; they will be deleted from here.
