### ISSUE TITLE
2nd monitor shows phantom menu bar in full-screen mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [classilla/tenfourfox#97]
```
Reported by some schlub at DeAnza. 10.5 only so far.
```

Original issue reported on code.google.com by `classi...@floodgap.com` on 14 Oct 2011 at 8:19

Attachments:
- [kevinpic.jpg](https://storage.googleapis.com/google-code-attachments/tenfourfox/issue-97/comment-0/kevinpic.jpg)

**Comment by classilla** [comment]
This appears to be related to bug 931826 https://bugzilla.mozilla.org/show_bug.cgi?id=931826 and/or bug 910144 https://bugzilla.mozilla.org/show_bug.cgi?id=910144 .

**Comment by classilla** [comment]
Also see note in nsCocoaUtils::HideOSChromeOnScreen.

**Comment by classilla** [comment]
Based on the comment in `nsCocoaUtils.mm` I think this is actually working as designed. There is some difference in the code from the 2015 report, so I'm going to close as wfm unless more info is received.
